/**
 * Share images.
 *
 * One card per route, generated by `scripts/build-og.mjs` and committed under
 * `public/og/`. This file is the only place that knows which route gets which
 * file, so a page cannot quietly end up advertising another page's picture.
 *
 * ---
 *
 * THESE PATHS DO NOT GO THROUGH `asset()`, AND THAT IS DELIBERATE
 *
 * Every other hand-written path to something in `public/` must be wrapped in
 * `asset()` to pick up `basePath` on a GitHub project page. These must not be,
 * because Next resolves a relative `openGraph.images` URL against
 * `metadataBase` — and the deploy workflow already builds that WITH the repo
 * segment in it:
 *
 *     site_url = https://<owner>.github.io/<repo>
 *
 * So `/og/home.png` resolves to `…github.io/<repo>/og/home.png`, which is the
 * file. Wrapping it in `asset()` as well would emit `…/<repo>/<repo>/og/…` and
 * every card on every platform would 404 — the more dangerous failure of the
 * two, because a broken share image is invisible from inside the site.
 *
 * ---
 *
 * ALT TEXT IS REQUIRED, NOT OPTIONAL
 *
 * The parameter has no default. A share image is the one image on this site
 * that arrives with no page around it to explain it — in a screen reader, in a
 * link preview, in a message someone forwards — so it is the one that least
 * survives being unlabelled.
 */

/** The size every card is rendered at, and the size crawlers are told. */
export const OG_SIZE = { width: 1200, height: 630 } as const;

type OgImage = {
  url: string;
  width: number;
  height: number;
  alt: string;
  type: string;
};

/**
 * The `openGraph.images` / `twitter.images` value for one card.
 *
 * `name` is the file's stem in `public/og/` — the same string
 * `scripts/build-og.mjs` writes, which is what keeps the two halves in step.
 */
export function ogImage(name: string, alt: string): OgImage[] {
  return [{ url: `/og/${name}.png`, ...OG_SIZE, alt, type: 'image/png' }];
}

/**
 * The diagram on each lesson's card, and what it shows.
 *
 * `scripts/build-og.mjs` imports this to pick which plate to draw, and
 * `notebook/[slug]` imports it to write the alt text — so the description can
 * never end up describing a picture that is no longer there. That was the whole
 * reason to put it here rather than keeping a copy in each.
 *
 * The alt says what is DRAWN, not what the lesson is about. Composing it from
 * the standfirst instead produced "What a derivative measures — What a
 * derivative measures, read off a graph…", because that entry's standfirst
 * opens with its own title — and it described the article rather than the
 * image either way, which is not what alt text is for.
 */
export const NOTEBOOK_CARD: Record<string, { plate: string; alt: string }> = {
  'designing-a-circuit-board': {
    plate: 'board',
    alt: 'a populated circuit board — copper traces, a pin header, and two labelled chips',
  },
  'monte-carlo-simulation': {
    plate: 'histogram',
    alt: 'a simulated distribution of outcomes, with the worst five percent marked off at the value-at-risk cut',
  },
  'physics-based-animation': {
    plate: 'spring',
    alt: 'a damped spring rising to its target, overshooting once, and settling',
  },
  'what-a-derivative-measures': {
    plate: 'curve',
    alt: 'the parabola f(x) = x squared, with a straight line touching it at x = 1',
  },
  'modelling-credit-risk': {
    plate: 'credit',
    alt: 'expected loss by borrower tier, the subprime bar tallest despite being the smallest group',
  },
  'logistic-regression-on-market-returns': {
    plate: 'sigmoid',
    alt: 'the logistic curve, flat at nought and one and crossing a half at zero',
  },
};
