/**
 * Share images.
 *
 * One card per route, generated by `scripts/build-og.mjs` and committed under
 * `public/og/`. This file is the only place that knows which route gets which
 * file, so a page cannot quietly end up advertising another page's picture.
 *
 * ---
 *
 * THESE PATHS DO NOT GO THROUGH `asset()`, AND THAT IS DELIBERATE
 *
 * Every other hand-written path to something in `public/` must be wrapped in
 * `asset()` to pick up `basePath` on a GitHub project page. These must not be,
 * because Next resolves a relative `openGraph.images` URL against
 * `metadataBase` — and the deploy workflow already builds that WITH the repo
 * segment in it:
 *
 *     site_url = https://<owner>.github.io/<repo>
 *
 * So `/og/home.png` resolves to `…github.io/<repo>/og/home.png`, which is the
 * file. Wrapping it in `asset()` as well would emit `…/<repo>/<repo>/og/…` and
 * every card on every platform would 404 — the more dangerous failure of the
 * two, because a broken share image is invisible from inside the site.
 *
 * ---
 *
 * ALT TEXT IS REQUIRED, NOT OPTIONAL
 *
 * The parameter has no default. A share image is the one image on this site
 * that arrives with no page around it to explain it — in a screen reader, in a
 * link preview, in a message someone forwards — so it is the one that least
 * survives being unlabelled.
 */

/** The size every card is rendered at, and the size crawlers are told. */
export const OG_SIZE = { width: 1200, height: 630 } as const;

type OgImage = {
  url: string;
  width: number;
  height: number;
  alt: string;
  type: string;
};

/**
 * The `openGraph.images` / `twitter.images` value for one card.
 *
 * `name` is the file's stem in `public/og/` — the same string
 * `scripts/build-og.mjs` writes, which is what keeps the two halves in step.
 */
export function ogImage(name: string, alt: string): OgImage[] {
  return [{ url: `/og/${name}.png`, ...OG_SIZE, alt, type: 'image/png' }];
}
