import type { Category } from './types';

export const dp1d: Category = {
  slug: '1d-dp',
  title: '1-D Dynamic Programming',
  blurb: 'When the answer for n is built from answers for smaller n, compute each one once and keep it. A row of remembered answers, filled in order.',
  problems: [
    {
      slug: 'climbing-stairs',
      number: 70,
      title: 'Climbing Stairs',
      difficulty: 'Easy',
      statement: ['A staircase has `n` steps. Each move climbs one step or two. Return the number of different ways to reach the top.'],
      constraints: ['1 ≤ n ≤ 45'],
      idea: [
        'Look at the last move. It either came from step `n − 1` (one step) or from step `n − 2` (two). Every route is one or the other, never both, so ways(n) = ways(n − 1) + ways(n − 2). With ways(0) = 1 and ways(1) = 1, this is the Fibonacci sequence.',
        'Computing that by recursion alone repeats the same values over and over — exponentially many calls. Dynamic programming computes each value once, smallest first; and since each needs only the two before it, two variables are enough. For n = 5: 1, 1, 2, 3, 5, 8.',
      ],
      complexity: { time: 'O(n)', space: 'O(1) — two numbers' },
    },
    {
      slug: 'min-cost-climbing-stairs',
      number: 746,
      title: 'Min Cost Climbing Stairs',
      difficulty: 'Easy',
      statement: [
        'Step `i` of a staircase costs `cost[i]` to leave. From a step you climb one or two steps. You may start on step 0 or step 1.',
        'Return the least total cost to reach the top, just past the last step.',
      ],
      constraints: ['2 ≤ cost.length ≤ 1000', '0 ≤ cost[i] ≤ 999'],
      idea: [
        'Let reach(i) be the cheapest way to be standing on step i; the top is step n, and reach(0) = reach(1) = 0 since you may start there.',
        'You arrive at step i from i − 1, paying `cost[i − 1]`, or from i − 2, paying `cost[i − 2]`: reach(i) = min(reach(i − 1) + cost[i − 1], reach(i − 2) + cost[i − 2]). Fill it upwards, keeping only the last two values.',
      ],
      complexity: { time: 'O(n)', space: 'O(1)' },
    },
    {
      slug: 'house-robber',
      number: 198,
      title: 'House Robber',
      difficulty: 'Medium',
      statement: [
        'Houses along a street hold `nums[i]` in money. Robbing two neighbouring houses sets off an alarm.',
        'Return the most money you can take without robbing two neighbours.',
      ],
      constraints: ['1 ≤ nums.length ≤ 100', '0 ≤ nums[i] ≤ 400'],
      idea: [
        'Let best(i) be the most from houses 0 to i. For house i there are two choices: leave it, and take best(i − 1); or rob it, which rules out house i − 1, and take best(i − 2) + nums[i].',
        'best(i) = max(best(i − 1), best(i − 2) + nums[i]). Walk the street once, keeping the last two values. For [2, 7, 9, 3, 1]: 2, 7, 11, 11, 12.',
      ],
      complexity: { time: 'O(n)', space: 'O(1)' },
    },
    {
      slug: 'house-robber-ii',
      number: 213,
      title: 'House Robber II',
      difficulty: 'Medium',
      statement: ['As in House Robber, but the houses stand in a circle: the first and the last are neighbours too. Return the most money you can take without robbing two neighbours.'],
      constraints: ['1 ≤ nums.length ≤ 100', '0 ≤ nums[i] ≤ 1000'],
      idea: [
        'The circle adds one rule: the first and last houses cannot both be robbed. So at least one of them is left alone.',
        'If the last is left alone, the problem is House Robber on houses 0 to n − 2; if the first is, on houses 1 to n − 1. Solve both straight streets and take the better. (A single house is its own answer.)',
      ],
      complexity: { time: 'O(n) — two passes', space: 'O(1)' },
    },
    {
      slug: 'longest-palindromic-substring',
      number: 5,
      title: 'Longest Palindromic Substring',
      difficulty: 'Medium',
      statement: ['A palindrome reads the same forwards and backwards. Given a string `s`, return its longest substring (a run of consecutive characters) that is a palindrome. If there are several of that length, any one will do.'],
      constraints: ['1 ≤ s.length ≤ 1000', 'Digits and English letters only.'],
      idea: [
        'Every palindrome has a centre; growing outwards from each of the 2n − 1 centres finds them all, in O(n²). Manacher’s algorithm does it in O(n). First put `#` between the letters and at both ends — `abba` becomes `#a#b#b#a#` — so every palindrome, odd or even, has one character at its centre. `p[i]` records how far the palindrome centred at `i` reaches.',
        'Keep the palindrome that reaches furthest right, centred at `center`, ending at `right`. For a new centre `i` inside it, its mirror `2·center − i` has already been measured, and the big palindrome guarantees `i` matches at least `min(p[mirror], right − i)` — so start there instead of at 0, and only then compare letters. Every comparison that succeeds pushes `right` further, and `right` never moves back, so the comparisons total O(n).',
      ],
      complexity: { time: 'O(n)', space: 'O(n) — the reach of each centre' },
    },
    {
      slug: 'palindromic-substrings',
      number: 647,
      title: 'Palindromic Substrings',
      difficulty: 'Medium',
      statement: ['Given a string `s`, return how many of its substrings are palindromes. Substrings at different positions count separately, even if they are the same letters.'],
      constraints: ['1 ≤ s.length ≤ 1000', 'Only lowercase English letters.'],
      idea: [
        'Run Manacher’s algorithm, as in Longest Palindromic Substring, to find for every centre the longest palindrome around it.',
        'Around one centre, every shorter palindrome is the long one with equal amounts trimmed from each end — so a centre whose longest palindrome has length `p[i]` in `s` accounts for ⌈p[i] ÷ 2⌉ palindromes (the ⌈ ⌉ means round up). In `aaa`, the centre on the middle `a` reaches length 3: “a” and “aaa”, 2 = ⌈3 ÷ 2⌉. Add them up over all centres.',
      ],
      complexity: { time: 'O(n)', space: 'O(n)' },
    },
    {
      slug: 'decode-ways',
      number: 91,
      title: 'Decode Ways',
      difficulty: 'Medium',
      statement: [
        'Letters are encoded as numbers: A is 1, B is 2, …, Z is 26. A string of digits can often be read back several ways — `12` is AB (1, 2) or L (12).',
        'Given the digits `s`, return the number of ways to decode it. A group may not start with 0, so `06` cannot be read.',
      ],
      constraints: ['1 ≤ s.length ≤ 100', '`s` contains only digits and may start with 0.'],
      idea: [
        'Let ways(i) count the decodings of the digits from position i to the end. The first letter uses either one digit — any of 1–9 — leaving ways(i + 1); or two digits forming 10–26, leaving ways(i + 2).',
        'So ways(i) = [s[i] ≠ 0] · ways(i + 1) + [s[i..i+1] is 10–26] · ways(i + 2), where [ ] is 1 when true and 0 when false, and the empty end decodes exactly one way. Fill it from the end backwards, keeping two values. For `226`, working from the end: the empty end is 1 way; `6` is 1; `26` is 1 + 1 = 2 (2 6, or 26); `226` is 2 + 1 = 3.',
      ],
      complexity: { time: 'O(n)', space: 'O(1)' },
    },
    {
      slug: 'coin-change',
      number: 322,
      title: 'Coin Change',
      difficulty: 'Medium',
      statement: ['Given coin values `coins` (as many of each as you like) and an `amount`, return the fewest coins that add up to exactly `amount`, or −1 if it cannot be made.'],
      constraints: ['1 ≤ coins.length ≤ 12', '1 ≤ coins[i] ≤ 2³¹ − 1', '0 ≤ amount ≤ 10⁴'],
      idea: [
        'Taking the biggest coin first can fail: with coins 1, 3, 4 and amount 6, greedy gives 4 + 1 + 1 (three coins) but 3 + 3 is two.',
        'Instead, let fewest[x] be the fewest coins making x. The last coin used is some `c`, and what is left, `x − c`, must itself be made as cheaply as possible: fewest[x] = 1 + the smallest fewest[x − c] over coins c ≤ x. Fill it from 0 (which needs none) up to `amount`; an amount no coin combination makes stays at “infinity” — here, amount + 1, more coins than could ever be needed.',
      ],
      complexity: { time: 'O(amount × number of coins)', space: 'O(amount)' },
    },
    {
      slug: 'maximum-product-subarray',
      number: 152,
      title: 'Maximum Product Subarray',
      difficulty: 'Medium',
      statement: ['Given an integer array `nums`, return the largest product of any subarray — a run of one or more consecutive elements.'],
      constraints: ['1 ≤ nums.length ≤ 2 × 10⁴', '−10 ≤ nums[i] ≤ 10', 'Every product of a prefix or suffix fits in a 32-bit integer.'],
      idea: [
        'For sums, the best run ending here is the best run ending just before, extended — or a fresh start. Products add a twist: multiplying by a negative number turns the largest product into the smallest and the smallest (most negative) into the largest.',
        'So keep both: `hi` and `lo`, the largest and smallest products of a run ending at the current element. The new ones are the largest and smallest of: the element alone, `hi × x`, and `lo × x`. The answer is the largest `hi` seen. For [2, 3, −2, 4]: hi goes 2, 6, −2, 4 and lo 2, 3, −12, −48; the best is 6.',
      ],
      complexity: { time: 'O(n)', space: 'O(1)' },
    },
    {
      slug: 'word-break',
      number: 139,
      title: 'Word Break',
      difficulty: 'Medium',
      statement: ['Given a string `s` and a list of words `wordDict`, return `true` if `s` can be split into a sequence of one or more dictionary words, each used as often as needed.'],
      constraints: ['1 ≤ s.length ≤ 300', '1 ≤ wordDict.length ≤ 1000', '1 ≤ wordDict[i].length ≤ 20', 'Lowercase letters; the words are all different.'],
      idea: [
        'Let ok[i] say whether the first `i` characters can be split into words. ok[0] is true — nothing needs no words. The first `i` characters split if some word ends exactly at `i` and the part before it splits: ok[i] = ok[j] and s[j..i) is a word, for some j.',
        'No word is longer than the longest in the dictionary, so only that many `j`s need checking for each `i`. Put the words in a hash set so each check is one lookup.',
      ],
      complexity: { time: 'O(n · L · L) — n positions, L starting points each, and an L-letter substring to hash', space: 'O(n + total letters in the dictionary)' },
    },
    {
      slug: 'longest-increasing-subsequence',
      number: 300,
      title: 'Longest Increasing Subsequence',
      difficulty: 'Medium',
      statement: [
        'A subsequence keeps some elements of an array in their original order, not necessarily next to each other. Given `nums`, return the length of the longest subsequence whose values strictly increase.',
      ],
      constraints: ['1 ≤ nums.length ≤ 2500', '−10⁴ ≤ nums[i] ≤ 10⁴'],
      idea: [
        'The O(n²) way asks, for each element, what is the longest increasing run ending there. A sharper question: for each length k, what is the smallest value an increasing run of that length can end with? Call it tails[k]. A smaller ending is always better — it leaves more room to extend.',
        'tails only ever increases along its length, so each new number `x` finds its place by binary search: the first tail ≥ x. If there is none, `x` extends the longest run and tails grows; otherwise `x` replaces that tail — a run of that length can now end lower. The length of tails is the answer (tails itself need not be a real subsequence).',
      ],
      complexity: { time: 'O(n log n)', space: 'O(n)' },
    },
    {
      slug: 'partition-equal-subset-sum',
      number: 416,
      title: 'Partition Equal Subset Sum',
      difficulty: 'Medium',
      statement: ['Given an array of positive integers `nums`, return `true` if it can be split into two groups with equal sums.'],
      constraints: ['1 ≤ nums.length ≤ 200', '1 ≤ nums[i] ≤ 100'],
      idea: [
        'Two equal groups each sum to half the total. So an odd total is impossible, and otherwise the question is: does some selection of the numbers add up to `half`?',
        'Let can[s] say whether some of the numbers seen so far add up to `s`, starting with only can[0] true. Each new number `x` makes s reachable if s − x already was. Update `s` from high to low, so the `can[s − x]` being read is still from before `x` — otherwise `x` could be used twice. Stop as soon as can[half] is true.',
      ],
      complexity: { time: 'O(n × half)', space: 'O(half)' },
    },
  ],
};
