import type { Category } from './types';

export const dp2d: Category = {
  slug: '2d-dp',
  title: '2-D Dynamic Programming',
  blurb: 'Two things change at once — a position in each of two strings, a row and a column, an index and an amount — so the remembered answers form a table.',
  problems: [
    {
      slug: 'unique-paths',
      number: 62,
      title: 'Unique Paths',
      difficulty: 'Medium',
      statement: ['A robot stands in the top-left cell of an `m × n` grid and must reach the bottom-right cell, moving only down or right. Return the number of different paths.'],
      constraints: ['1 ≤ m, n ≤ 100', 'The answer is at most 2 × 10⁹.'],
      idea: [
        'The table way: the paths into a cell are the paths into the cell above plus those into the cell to its left — Pascal’s triangle, m × n steps. But the table has a closed form.',
        'Every path is exactly `m − 1` moves down and `n − 1` moves right, in some order; choosing which of the `m + n − 2` moves are the downs fixes the path. That is the binomial coefficient C(m + n − 2, m − 1) — “m + n − 2 choose m − 1”. For a 3 × 7 grid: C(8, 2) = 8 × 7 ÷ 2 = 28. Multiplying in and dividing one factor at a time keeps every intermediate value a whole number, since after step i it equals C(·, i).',
      ],
      complexity: { time: 'O(min(m, n))', space: 'O(1)' },
    },
    {
      slug: 'longest-common-subsequence',
      number: 1143,
      title: 'Longest Common Subsequence',
      difficulty: 'Medium',
      statement: ['A subsequence keeps some characters of a string in order, not necessarily next to each other: `ace` is one of `abcde`. Given `text1` and `text2`, return the length of the longest subsequence they share, or 0 if none.'],
      constraints: ['1 ≤ text1.length, text2.length ≤ 1000', 'Only lowercase English letters.'],
      idea: [
        'Let lcs(i, j) be the answer for the first i letters of text1 and the first j of text2. If their last letters match, both can end the common subsequence: 1 + lcs(i − 1, j − 1). If not, at least one of them is unused: max(lcs(i − 1, j), lcs(i, j − 1)).',
        'That fills a table row by row, each cell from the one above, the one to the left and the one diagonally up-left. Only the previous row is ever read, so one row, overwritten in place, is enough — with the up-left value saved before it is overwritten.',
      ],
      complexity: { time: 'O(m · n)', space: 'O(n) — one row' },
    },
    {
      slug: 'best-time-to-buy-and-sell-stock-with-cooldown',
      number: 309,
      title: 'Best Time to Buy and Sell Stock with Cooldown',
      difficulty: 'Medium',
      statement: [
        '`prices[i]` is a stock’s price on day `i`. You may buy and sell as many times as you like, but hold at most one share at a time, and after selling you must wait a day (a cooldown) before buying again.',
        'Return the most profit you can make.',
      ],
      constraints: ['1 ≤ prices.length ≤ 5000', '0 ≤ prices[i] ≤ 1000'],
      idea: [
        'At the end of each day you are in one of three states: holding a share, having just sold one today, or resting with none (free to buy tomorrow). Track the best profit for each.',
        'Tomorrow: hold = max(keep holding, buy from rest — rest − price); sold = hold + price; rest = max(keep resting, come off yesterday’s sale). Buying only from rest, never straight from sold, is the cooldown. The answer is the better of sold and rest at the end.',
      ],
      complexity: { time: 'O(n)', space: 'O(1) — three numbers' },
    },
    {
      slug: 'coin-change-ii',
      number: 518,
      title: 'Coin Change II',
      difficulty: 'Medium',
      statement: ['Given coin values `coins` (as many of each as you like) and an `amount`, return the number of different combinations of coins that make up `amount`. The order of coins does not matter: 1 + 2 and 2 + 1 are one combination.'],
      constraints: ['1 ≤ coins.length ≤ 300', '1 ≤ coins[i] ≤ 5000, all different', '0 ≤ amount ≤ 5000', 'The answer fits in a 32-bit signed integer.'],
      idea: [
        'Counting orderings would be easy and wrong. To count each combination once, decide the coins one kind at a time: first how many 1s, then how many 2s, and so on. ways[x] counts combinations of x using only the kinds considered so far.',
        'Adding a kind `c`: combinations of x now either use no `c` (the old ways[x]) or at least one, leaving x − c made with kinds up to and including `c` (the new ways[x − c]). Updating x upwards reads the new value, so `c` can repeat. Only the final answer is promised to fit in 32 bits; the solutions add modulo 2³² where the language would otherwise overflow, which leaves that final answer exact.',
      ],
      complexity: { time: 'O(amount × number of coins)', space: 'O(amount)' },
    },
    {
      slug: 'target-sum',
      number: 494,
      title: 'Target Sum',
      difficulty: 'Medium',
      statement: ['Put a `+` or a `−` in front of each number in `nums`, and add them up. Return the number of ways to choose the signs so the total is `target`.'],
      constraints: ['1 ≤ nums.length ≤ 20', '0 ≤ nums[i] ≤ 1000', 'The numbers sum to at most 1000.', '−1000 ≤ target ≤ 1000'],
      idea: [
        'Call the numbers given `+` the group P and those given `−` the group N. Then P − N = target and P + N = total. Adding the two: P = (total + target) ÷ 2. So the question is just how many subsets add up to that — and if total + target is odd, or target is out of reach, the answer is 0.',
        'Count subsets with sum s as in Partition Equal Subset Sum, but counting instead of yes/no: each number x adds ways[s − x] to ways[s], going downwards so x is used once. A 0 doubles every count, since +0 and −0 are both fine.',
      ],
      complexity: { time: 'O(n × total)', space: 'O(total)' },
    },
    {
      slug: 'interleaving-string',
      number: 97,
      title: 'Interleaving String',
      difficulty: 'Medium',
      statement: ['Return `true` if `s3` can be made by interleaving `s1` and `s2`: taking all the characters of both and mixing them together, while each keeps its own order. `aadbc` interleaves `abc` and `ad`: a, a, d, b, c.'],
      constraints: ['0 ≤ s1.length, s2.length ≤ 100', '0 ≤ s3.length ≤ 200', 'Only lowercase English letters.'],
      idea: [
        'The lengths must add up. Then let ok(i, j) say whether the first i letters of s1 and the first j of s2 can interleave into the first i + j letters of s3. The last of those letters came either from s1 — it must equal s1’s i-th letter, and ok(i − 1, j) must hold — or from s2, likewise with ok(i, j − 1).',
        'Picture a grid where moving down takes a letter from s1 and moving right takes one from s2: the question is whether some path reaches the corner. One row at a time suffices.',
      ],
      complexity: { time: 'O(m · n)', space: 'O(n)' },
    },
    {
      slug: 'longest-increasing-path-in-a-matrix',
      number: 329,
      title: 'Longest Increasing Path in a Matrix',
      difficulty: 'Hard',
      statement: ['Given an `m × n` matrix of integers, return the number of cells in the longest path that moves up, down, left or right, always to a strictly larger value.'],
      constraints: ['1 ≤ m, n ≤ 200', '0 ≤ matrix[i][j] ≤ 2³¹ − 1'],
      idea: [
        'Draw an arrow from each cell to every larger neighbour. Arrows only go uphill, so they can never loop — the longest path is well defined, and can be found by peeling the matrix in layers, as Kahn’s algorithm does.',
        'Count, for each cell, its smaller neighbours. Cells with none are where paths begin: layer 1. Remove them; every cell whose count drops to 0 is layer 2, and so on. The number of layers is the length of the longest path. (A depth-first search that remembers each cell’s answer works as well, but on a 200 × 200 matrix its recursion can run 40,000 calls deep.)',
      ],
      complexity: { time: 'O(m · n)', space: 'O(m · n)' },
    },
    {
      slug: 'distinct-subsequences',
      number: 115,
      title: 'Distinct Subsequences',
      difficulty: 'Hard',
      statement: ['Given strings `s` and `t`, return the number of different ways to pick characters of `s`, in order, that spell `t`. Picks that use different positions count separately.'],
      constraints: ['1 ≤ s.length, t.length ≤ 1000', 'English letters only.', 'The answer fits in a 32-bit signed integer.'],
      idea: [
        'Read s one letter at a time, keeping ways[j]: the number of ways to spell the first j letters of t from what has been read. Each new letter can be skipped — every count stays — or, if it equals t’s j-th letter, used to finish a copy of t[0..j), adding ways[j − 1].',
        'Update j from high to low, so the letter just read is not used twice. The empty prefix of t is spelled exactly one way. The intermediate counts can outgrow 32 bits even when the answer does not; since only additions are involved, counting modulo 2³² still ends on the exact answer.',
      ],
      complexity: { time: 'O(m · n)', space: 'O(n)' },
    },
    {
      slug: 'edit-distance',
      number: 72,
      title: 'Edit Distance',
      difficulty: 'Medium',
      statement: ['Return the fewest operations that turn `word1` into `word2`, where an operation inserts a character, deletes a character, or replaces one character with another.'],
      constraints: ['0 ≤ word1.length, word2.length ≤ 500', 'Only lowercase English letters.'],
      idea: [
        'Let d(i, j) be the edits turning the first i letters of word1 into the first j of word2. Turning into or from an empty word takes j inserts or i deletes. If the last letters match, they cost nothing: d(i − 1, j − 1).',
        'Otherwise the last step was one of three: delete word1’s last letter (d(i − 1, j)), insert word2’s last letter (d(i, j − 1)), or replace one with the other (d(i − 1, j − 1)) — 1 plus the cheapest. For `horse` → `ros` the table ends at 3: replace h with r, delete r, delete e.',
      ],
      complexity: { time: 'O(m · n)', space: 'O(n) — one row' },
    },
    {
      slug: 'burst-balloons',
      number: 312,
      title: 'Burst Balloons',
      difficulty: 'Hard',
      statement: [
        'Balloons in a row carry numbers `nums[i]`. Bursting balloon i earns `left × nums[i] × right`, where left and right are the numbers on its current neighbours; past either end, count 1. Burst balloons close the gap.',
        'Return the most coins you can collect by bursting them all.',
      ],
      constraints: ['1 ≤ nums.length ≤ 300', '0 ≤ nums[i] ≤ 100'],
      idea: [
        'Thinking about the first balloon to burst fails: afterwards its neighbours touch, and the two sides are no longer separate problems. Think about the last one instead. If k is the last balloon burst between walls l and r, then while everything else between them is being burst, k stands in the way — the left part and the right part never meet, and k’s own burst then earns `v[l] × v[k] × v[r]`.',
        'So best(l, r) — the most from bursting everything strictly between l and r — is the largest of `best(l, k) + v[l] × v[k] × v[r] + best(k, r)` over each k between them. Pad the row with a 1 at each end, and fill the table from short ranges to long.',
      ],
      complexity: { time: 'O(n³)', space: 'O(n²)' },
    },
    {
      slug: 'regular-expression-matching',
      number: 10,
      title: 'Regular Expression Matching',
      difficulty: 'Hard',
      statement: [
        'Match a string `s` against a pattern `p` in which `.` matches any single character and `x*` matches zero or more copies of the character before it. The pattern must match the whole of `s`, not just part of it.',
      ],
      constraints: ['1 ≤ s.length ≤ 20', '1 ≤ p.length ≤ 20', '`s` is lowercase letters; `p` is lowercase letters, `.` and `*`.', 'Every `*` follows a character it can repeat.'],
      idea: [
        'Let match(i, j) say whether the rest of s from i matches the rest of p from j. When p runs out, it matches only if s has too. Otherwise, `first` says whether s[i] exists and equals p[j] (or p[j] is `.`).',
        'If p[j] is followed by `*`, there are two readings: use `x*` zero times and skip it — match(i, j + 2) — or, if `first`, let it eat s[i] and stay on the same pattern — match(i + 1, j). Without a `*`, `first` must hold and both move on: match(i + 1, j + 1). Filling the table from the ends back to the start means every value it needs is ready.',
      ],
      complexity: { time: 'O(m · n)', space: 'O(m · n)' },
    },
  ],
};
