import type { Category } from './types';

export const trees: Category = {
  slug: 'trees',
  title: 'Trees',
  blurb: 'A tree is a node and two smaller trees. Solve it for one node, trust the same function on the children, and the whole tree is solved.',
  problems: [
    {
      slug: 'invert-binary-tree',
      number: 226,
      title: 'Invert Binary Tree',
      difficulty: 'Easy',
      statement: [
        'A binary tree is made of nodes, each holding a value and at most two children, `left` and `right`; the top node is the `root`. Here a tree is written level by level, left to right, with `null` for a missing child.',
        'Given the `root`, mirror the tree — swap every node’s left and right children, all the way down — and return its root.',
      ],
      constraints: ['0 ≤ number of nodes ≤ 100', '−100 ≤ Node.val ≤ 100'],
      idea: [
        'The mirror of a tree is: the same root, with the mirror of its right subtree on the left and the mirror of its left subtree on the right.',
        'That sentence is the code. Recursion — a function calling itself on a smaller piece — does the rest: each call swaps one node’s children and trusts the calls below to mirror theirs. An empty tree is its own mirror, which stops it.',
      ],
      complexity: { time: 'O(n) — each node is swapped once', space: 'O(h) — the calls waiting on the way down, h the tree’s height' },
    },
    {
      slug: 'maximum-depth-of-binary-tree',
      number: 104,
      title: 'Maximum Depth of Binary Tree',
      difficulty: 'Easy',
      statement: ['Given the `root` of a binary tree, return its maximum depth: the number of nodes on the longest path from the root down to a leaf (a node with no children).'],
      constraints: ['0 ≤ number of nodes ≤ 10⁴', '−100 ≤ Node.val ≤ 100'],
      idea: [
        'The depth of a tree is one (for the root) plus the depth of its deeper subtree. The depth of an empty tree is 0.',
        'A depth-first search — going all the way down one branch before trying the next — computes the depths from the leaves back up: every node learns its children’s depths, then reports its own.',
      ],
      complexity: { time: 'O(n)', space: 'O(h) — h the height, n on a tree that is one long line' },
    },
    {
      slug: 'diameter-of-binary-tree',
      number: 543,
      title: 'Diameter of Binary Tree',
      difficulty: 'Easy',
      statement: [
        'The diameter of a binary tree is the length of the longest path between any two nodes, counted in edges (the links between nodes). The path does not have to pass through the root.',
        'Given the `root`, return the diameter.',
      ],
      constraints: ['1 ≤ number of nodes ≤ 10⁴', '−100 ≤ Node.val ≤ 100'],
      idea: [
        'Every path has one highest node, where it bends: it goes down the left side and down the right. At a node, the longest path bending there is the height of its left subtree plus the height of its right.',
        'So compute heights bottom-up (as in Maximum Depth), and at each node, while its two heights are in hand, record `left + right` if it beats the best so far. One pass finds the answer.',
      ],
      complexity: { time: 'O(n)', space: 'O(h)' },
    },
    {
      slug: 'balanced-binary-tree',
      number: 110,
      title: 'Balanced Binary Tree',
      difficulty: 'Easy',
      statement: ['A binary tree is height-balanced if, at every node, the heights of its left and right subtrees differ by at most one. Given the `root`, return whether the tree is height-balanced.'],
      constraints: ['0 ≤ number of nodes ≤ 5000', '−10⁴ ≤ Node.val ≤ 10⁴'],
      idea: [
        'Checking each node by computing its subtrees’ heights from scratch repeats work: n nodes, each measuring up to n below it.',
        'Instead compute every height once, bottom-up, and let a node report −1 — “unbalanced” — if either child did, or if its children’s heights differ by more than one. The −1 rises straight to the root, so one pass answers the question.',
      ],
      complexity: { time: 'O(n)', space: 'O(h)' },
    },
    {
      slug: 'same-tree',
      number: 100,
      title: 'Same Tree',
      difficulty: 'Easy',
      statement: ['Given the roots of two binary trees, `p` and `q`, return `true` if they are the same: the same shape, with the same values in the same places.'],
      constraints: ['0 ≤ nodes in each tree ≤ 100', '−10⁴ ≤ Node.val ≤ 10⁴'],
      idea: [
        'Two trees are the same when both are empty, or when both roots hold the same value and the left subtrees are the same and the right subtrees are the same.',
        'Walk both together. The first mismatch — one node missing where the other exists, or two different values — answers `false` at once.',
      ],
      complexity: { time: 'O(n) — each pair of nodes compared once', space: 'O(h)' },
    },
    {
      slug: 'subtree-of-another-tree',
      number: 572,
      title: 'Subtree of Another Tree',
      difficulty: 'Easy',
      statement: ['Given the roots of two binary trees, `root` and `subRoot`, return `true` if `root` contains a subtree — some node together with everything below it — identical to `subRoot`.'],
      constraints: ['1 ≤ nodes in root ≤ 2000', '1 ≤ nodes in subRoot ≤ 1000', '−10⁴ ≤ Node.val ≤ 10⁴'],
      idea: [
        'Comparing `subRoot` against every node of `root` works but costs m × n. Instead turn both trees into text and search the text.',
        'Write a tree in preorder (node, then left, then right), with `#` for every missing child and `^` before every value, so `^1` can never be mistaken for the end of `^21`. With the gaps written in, the text fixes the tree exactly, and a subtree is precisely a run of its tree’s text. The Knuth–Morris–Pratt search finds a run in linear time: when a match fails part-way, a precomputed table says how much of what was matched can still be reused, so the text is never re-read.',
      ],
      complexity: { time: 'O(m + n) — writing both trees and one linear search', space: 'O(m + n) — the two texts' },
    },
    {
      slug: 'lowest-common-ancestor-of-a-binary-search-tree',
      number: 235,
      title: 'Lowest Common Ancestor of a Binary Search Tree',
      difficulty: 'Medium',
      statement: [
        'A binary search tree (BST) keeps, at every node, smaller values in the left subtree and larger ones in the right.',
        'Given a BST and two of its nodes, `p` and `q`, return their lowest common ancestor: the deepest node that has both of them below it (a node counts as below itself).',
      ],
      constraints: ['2 ≤ number of nodes ≤ 10⁵', '−10⁹ ≤ Node.val ≤ 10⁹', 'All values are different.', '`p` ≠ `q`, and both are in the tree.'],
      idea: [
        'Start at the root. If both values are smaller than this node, both nodes are in its left subtree, so the answer is there too; if both are larger, it is on the right.',
        'Otherwise they split here — one goes left and one right, or one of them is this very node — and no deeper node can have both below it. That node is the answer. Only one path is walked, and nothing is stored.',
      ],
      complexity: { time: 'O(h) — one path from the root', space: 'O(1)' },
    },
    {
      slug: 'binary-tree-level-order-traversal',
      number: 102,
      title: 'Binary Tree Level Order Traversal',
      difficulty: 'Medium',
      statement: ['Given the `root` of a binary tree, return its values level by level: a list per level, from the top down, each read left to right.'],
      constraints: ['0 ≤ number of nodes ≤ 2000', '−1000 ≤ Node.val ≤ 1000'],
      idea: [
        'Breadth-first search visits a tree level by level. It keeps a queue — a line where the first in is the first out — of nodes waiting to be visited: take one from the front, add its children at the back.',
        'To keep levels apart, note how many nodes are in the queue at the start of a level: exactly that many belong to it. Take that many, collect their values, and their children form the next level behind them.',
      ],
      complexity: { time: 'O(n)', space: 'O(w) — the widest level, up to about n ÷ 2' },
    },
    {
      slug: 'binary-tree-right-side-view',
      number: 199,
      title: 'Binary Tree Right Side View',
      difficulty: 'Medium',
      statement: ['Imagine standing to the right of a binary tree. Given its `root`, return the values of the nodes you can see, from top to bottom.'],
      constraints: ['0 ≤ number of nodes ≤ 100', '−100 ≤ Node.val ≤ 100'],
      idea: [
        'On each level, you see exactly one node: the rightmost. It need not be a right child — if the right side of the tree is short, a node from the left shows through below it.',
        'So go level by level, as in Level Order Traversal, and keep only the last node of each level.',
      ],
      complexity: { time: 'O(n)', space: 'O(w) — the widest level' },
    },
    {
      slug: 'count-good-nodes-in-binary-tree',
      number: 1448,
      title: 'Count Good Nodes in Binary Tree',
      difficulty: 'Medium',
      statement: ['A node is good if no node on the path from the root down to it has a larger value. Given the `root` of a binary tree, return the number of good nodes.'],
      constraints: ['1 ≤ number of nodes ≤ 10⁵', '−10⁴ ≤ Node.val ≤ 10⁴'],
      idea: [
        'Whether a node is good depends only on the largest value above it. So carry that number down.',
        'A depth-first search passes each child `best`, the largest value on the path so far. A node is good when its value is at least `best`; it then passes down the larger of `best` and its own value. The root is always good.',
      ],
      complexity: { time: 'O(n)', space: 'O(h)' },
    },
    {
      slug: 'validate-binary-search-tree',
      number: 98,
      title: 'Validate Binary Search Tree',
      difficulty: 'Medium',
      statement: [
        'Given the `root` of a binary tree, decide whether it is a valid binary search tree: for every node, every value in its left subtree is strictly smaller, every value in its right subtree strictly larger, and both subtrees are themselves valid.',
      ],
      constraints: ['1 ≤ number of nodes ≤ 10⁴', '−2³¹ ≤ Node.val ≤ 2³¹ − 1'],
      idea: [
        'Checking only that each child is on the correct side of its parent is not enough: in the tree `[5, 4, 6, null, null, 3, 7]`, the 3 is correctly left of 6 but sits on 5’s right, where everything must be larger than 5.',
        'So each node carries an allowed range, `lo < value < hi`, set by all its ancestors. The root may be anything. Going left, the node’s value becomes the new upper limit; going right, the new lower limit. The limits start beyond any possible value (a 64-bit number, or infinity), so the largest and smallest 32-bit values are still allowed.',
      ],
      complexity: { time: 'O(n)', space: 'O(h)' },
    },
    {
      slug: 'kth-smallest-element-in-a-bst',
      number: 230,
      title: 'Kth Smallest Element in a BST',
      difficulty: 'Medium',
      statement: ['Given the `root` of a binary search tree and a number `k`, return the `k`-th smallest value in the tree (counting from 1).'],
      constraints: ['1 ≤ k ≤ number of nodes ≤ 10⁴', '0 ≤ Node.val ≤ 10⁴'],
      idea: [
        'An in-order walk — left subtree, then the node, then the right subtree — visits a BST’s values in increasing order. So the k-th node it visits is the answer.',
        'Walk it with an explicit stack, so the walk can stop the moment the count reaches k: go left as far as possible, pushing each node; pop one — the next smallest — count it; then turn to its right subtree and repeat.',
      ],
      complexity: { time: 'O(h + k) — down to the smallest, then k steps', space: 'O(h) — the stack' },
    },
    {
      slug: 'construct-binary-tree-from-preorder-and-inorder-traversal',
      number: 105,
      title: 'Construct Binary Tree from Preorder and Inorder Traversal',
      difficulty: 'Medium',
      statement: [
        'Two ways to list a tree’s values: preorder (a node, then its left subtree, then its right) and inorder (the left subtree, then the node, then the right).',
        'Given both lists for the same tree, whose values are all different, build the tree and return its root.',
      ],
      constraints: ['1 ≤ preorder.length ≤ 3000', '`inorder` has the same length.', '−3000 ≤ value ≤ 3000, all different', 'Both lists come from the same tree.'],
      idea: [
        'Preorder puts a root first. Inorder puts that root between its two subtrees: everything before it in inorder is on the left, everything after on the right. So the first preorder value splits inorder into the two subtrees, and the same holds inside each.',
        'Build recursively over a range of inorder. Take the next preorder value as the root, look up where it sits in inorder (a hash map makes that one step), build the left part, then the right part. Preorder lists the left subtree entirely before the right, so reading preorder straight through hands every call its root in turn.',
      ],
      complexity: { time: 'O(n) — each value placed once', space: 'O(n) — the map' },
    },
    {
      slug: 'binary-tree-maximum-path-sum',
      number: 124,
      title: 'Binary Tree Maximum Path Sum',
      difficulty: 'Hard',
      statement: [
        'A path in a binary tree is a chain of nodes, each linked to the next, with no node used twice; it need not pass through the root and has at least one node. Its sum is the total of its values.',
        'Given the `root`, return the largest sum of any path. Values can be negative.',
      ],
      constraints: ['1 ≤ number of nodes ≤ 3 × 10⁴', '−1000 ≤ Node.val ≤ 1000'],
      idea: [
        'As in Diameter, every path bends at its highest node: down some way on the left, the node, down some way on the right. For each node, what matters is the best “gain” of a path going straight down from it.',
        'Compute gains bottom-up: a node’s gain is its value plus the larger of its children’s gains, where a negative gain is replaced by 0 — it is better to stop than to add a loss. At each node, `value + left gain + right gain` is the best path bending there; keep the largest.',
      ],
      complexity: { time: 'O(n)', space: 'O(h)' },
    },
    {
      slug: 'serialize-and-deserialize-binary-tree',
      number: 297,
      title: 'Serialize and Deserialize Binary Tree',
      difficulty: 'Hard',
      statement: [
        'Design `serialize`, which turns a binary tree into a string, and `deserialize`, which turns that string back into exactly the same tree. Any format will do, as long as the round trip is exact.',
      ],
      constraints: ['0 ≤ number of nodes ≤ 10⁴', '−1000 ≤ Node.val ≤ 1000'],
      idea: [
        'Values alone lose the shape — 1, 2 could be 2 on either side of 1. Writing a marker `#` for every missing child keeps it.',
        'Serialize in preorder: the value, then the whole left subtree, then the right, with `#` for each empty spot. Deserialize reads the tokens in the same order: a `#` is an empty tree; anything else is a node, whose left subtree is built from the tokens that follow, and then its right. Each call consumes exactly the tokens its subtree wrote.',
      ],
      complexity: { time: 'O(n) for both', space: 'O(n) — the string' },
    },
  ],
};
