/**
 * The résumé, as data.
 *
 * Single source for three artefacts: the modal on /founder, the PDF offered for
 * download, and the .docx generated by `scripts/build-resume.mjs`. They cannot
 * drift, because there is only one copy of the words.
 *
 * Every figure here comes from Rutvik's own record. Nothing is estimated or
 * rounded up to sound better — an interview will test these.
 */

// Relative, not the `@/` alias: `scripts/build-resume.mjs` imports this file
// with bare Node to generate the .docx and PDF, and bare Node cannot resolve
// tsconfig path aliases.
import { foundedYear, yearsOfExperienceLabel } from '../lib/time.ts';

export interface ResumeRole {
  company: string;
  location: string;
  role: string;
  /** MM/YYYY — ATS parsers key on this format. */
  start: string;
  end: string;
  /** One line of context before the achievements. */
  context: string;
  bullets: string[];
}

export const resumeHeader = {
  name: 'Rutvik Patel',
  /** Sits directly under the name: ATS keyword-matches the target job title. */
  title: 'Senior Frontend Engineer · Full-Stack Product Engineer',
  location: 'Toronto, Canada',
  phone: '647-637-9568',
  email: 'patelrutvik1702@gmail.com',
  linkedin: 'linkedin.com/in/rutvik1702',
  github: 'github.com/Rutvik17',
  site: 'rutvik17.github.io/seventeen-studios/founder',
} as const;

export const resumeSummary = `Senior frontend engineer with ${yearsOfExperienceLabel()} years building production interfaces for global enterprises and zero-to-one product teams. Architected a multi-tenant agentic AI platform at Ernst & Young, shipped a React Native product through to acquisition, and delivered connected-vehicle frontend architecture for Ford. Deep in React, Next.js and TypeScript, fluent across Node, Python and cloud infrastructure, with a record of measurable gains in performance, engagement and delivery speed.`;

export const resumeSkills: { group: string; items: string[] }[] = [
  {
    group: 'Languages',
    items: ['TypeScript', 'JavaScript (ES6+)', 'Python', 'Java', 'SQL', 'GLSL'],
  },
  {
    group: 'Frontend',
    items: [
      'React',
      'Next.js',
      'React Native',
      'Redux',
      'React Query',
      'Angular',
      'Nx',
      'RxJS',
      'Signals',
      'Tailwind CSS',
      'GSAP',
      'Three.js',
      'Storybook',
      'Vite',
    ],
  },
  {
    group: 'Backend & Data',
    items: [
      'Node.js',
      'REST APIs',
      'GraphQL',
      'Java Spring Boot',
      'PostgreSQL',
      'Supabase',
      'Microservices',
    ],
  },
  {
    group: 'Cloud & DevOps',
    items: [
      'Azure',
      'AWS (S3, Lambda, CloudFront)',
      'Docker',
      'CI/CD (GitHub Actions)',
      'Vercel',
      'Git',
    ],
  },
  {
    group: 'AI Engineering',
    items: [
      'LLM integration',
      'Agentic interfaces',
      'RAG pipelines',
      'Prompt engineering',
      'Evaluation harnesses',
    ],
  },
  {
    group: 'Quality & Practice',
    items: [
      'Jest',
      'React Testing Library',
      'Cypress',
      'Accessibility (WCAG)',
      'Design systems',
      'Agile / Scrum',
      'Mentorship',
    ],
  },
];

export const resumeExperience: ResumeRole[] = [
  {
    company: 'Ernst & Young',
    location: 'Remote · Toronto, Canada',
    role: 'Senior Frontend Engineer',
    start: '11/2023',
    end: 'Present',
    context:
      'Lead frontend engineer on an enterprise agentic AI platform — a chat-based environment used by global enterprise clients for automated risk analysis, report generation and decision support.',
    bullets: [
      'Architected a multi-tenant Next.js and React Query interface over Python microservices on Azure, improving data-retrieval performance by 40%.',
      `Built the frontend of an agentic AI platform for SAP ecosystem in Angular - standalone components, signals and zoneless change detection - within Nx monorepo, as the product's next generation stack.`,
      'Developed an interactive, schema-driven graph canvas for authoring and validating complex enterprise organizational structures, with automatic edge routing, live constraint validation, and inline create-edit-deploy workflows.',
      'Took LLM-powered authoring features from prototype to production - streaming generation, tool calling, and accept/reject review of AI-suggested edits in a collaborative rich text editor - partnering with product, design and platform teams.',
      'Implemented role-based access control across tenant hierarchies, isolating client data for enterprise customers across the EY ecosystem.',
      'Drove a storybook-based design system with token theming and enforced WCAG 2.2 AA via automated accessibility gates and frontend architecture fitness functions (style/bundle budgets, dependency boundaries); set frontend architecture standards and led code review.',
    ],
  },
  {
    company: 'Shop-Ware',
    location: 'Remote',
    role: 'React Native Engineer',
    start: '06/2022',
    end: '10/2023',
    context:
      'Owned the customer-facing mobile product from an empty repository through to the company’s acquisition.',
    bullets: [
      'Shipped the React Native application from zero to one across iOS and Android as the sole mobile engineer; the product contributed to a successful acquisition.',
      'Cut application load times by 20% on both platforms, tightening the daily feedback loop for end users.',
      'Established CI/CD pipelines and automated release processes, shipping more often with fewer regressions.',
    ],
  },
  {
    company: 'Nuvalence',
    location: 'Remote',
    role: 'Software Engineer',
    start: '11/2021',
    end: '06/2022',
    context:
      'Consulting engineer on two client platforms: connected vehicles at Ford and a public-sector modernisation for New York City.',
    bullets: [
      'Delivered the frontend architecture for Ford’s Connected Vehicle platform using React and Redux over Java microservices, improving user flows and page performance by 30%.',
      'Led development of a New York City government web system on Java Spring Boot, modernising critical workflows and reducing manual processing by 40%.',
    ],
  },
  {
    company: 'Mitel',
    location: 'Kanata, Ontario, Canada',
    role: 'UI/UX Software Developer',
    start: '11/2018',
    end: '10/2021',
    context:
      'Frontend developer on a unified-communications suite spanning desktop, web and mobile.',
    bullets: [
      'Modernised the interface of Mitel’s communication suite with React Native and Angular, lifting user engagement by 40%.',
      'Built a reusable component library adopted across all three platforms, cutting duplicated frontend code by 25% and standardising interaction patterns.',
    ],
  },
];

export const resumeProjects: {
  name: string;
  role: string;
  period: string;
  link: string;
  bullets: string[];
}[] = [
  {
    name: 'Seventeen Studios',
    role: 'Founder & Principal Engineer',
    period: `${foundedYear()} – Present`,
    link: 'rutvik17.github.io/seventeen-studios',
    bullets: [
      'Founded an independent engineering studio for product, creative and applied-AI engineering. Built the platform end to end: static Next.js export, custom GLSL and Three.js rendering, GSAP choreography, automated GitHub Actions deployment.',
    ],
  },
];

export const resumeEducation = {
  school: 'Centennial College',
  location: 'Toronto, Canada',
  credential: 'Associate in Applied Science (A.A.S.), Software Engineering',
  date: '06/2018',
} as const;
