/**
 * Checks the share images against the pages that reference them.
 *
 *   node scripts/verify-og.mjs [outDir]
 *
 * Runs in `postbuild`, beside `verify-drawing.mjs`. It reads the exported HTML
 * rather than the source, because the source is not what crawlers see.
 *
 * ---
 *
 * WHY THIS EXISTS
 *
 * The cards are generated by `npm run og` and committed, which means they can
 * fall out of step with the site in a way nothing else would notice. Add a
 * lesson and forget to regenerate, and that lesson's page ships pointing at a
 * PNG that is not in the export — and a broken share image is invisible from
 * inside the site. You do not find out until someone posts a link and it comes
 * up as a grey rectangle, and by then it has been wrong for weeks.
 *
 * So: every page must name one, every name must resolve to a file that is
 * actually in the build, and every URL must be absolute — a relative
 * `og:image` is rejected outright by most crawlers.
 *
 * It also reports cards nothing points at. That is a warning rather than a
 * failure: an unreferenced PNG is dead weight in the repository, not a broken
 * page, and a route may legitimately be mid-removal.
 */

import fs from 'node:fs';
import path from 'node:path';

const OUT = process.argv[2] ?? 'out';

function pages(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) =>
    entry.isDirectory()
      ? pages(path.join(dir, entry.name))
      : entry.name === 'index.html'
        ? [path.join(dir, entry.name)]
        : [],
  );
}

if (!fs.existsSync(OUT)) {
  console.error(`no export at ${OUT} — run the build first`);
  process.exit(1);
}

const failures = [];
const referenced = new Set();
let checked = 0;

for (const file of pages(OUT)) {
  const html = fs.readFileSync(file, 'utf8');
  const route = '/' + path.relative(OUT, path.dirname(file)).split(path.sep).join('/');
  const url = (html.match(/<meta property="og:image" content="([^"]+)"/) ?? [, ''])[1];

  checked++;

  if (!url) {
    failures.push(`${route} — no og:image`);
    continue;
  }

  if (!/^https?:\/\//.test(url)) {
    failures.push(`${route} — og:image is relative (${url}); crawlers need an absolute URL`);
    continue;
  }

  /*
    Strip the origin and look for the file in the export. This is the check that
    catches a stale `metadataBase`/`basePath` combination as well as a missing
    card — if the two ever double up the repo segment, the path stops resolving
    here rather than in production.
  */
  const rel = url.replace(/^https?:\/\/[^/]+/, '');
  const onDisk = path.join(OUT, rel);
  if (!fs.existsSync(onDisk)) {
    failures.push(`${route} — og:image does not resolve to a file in the export: ${rel}`);
    continue;
  }
  referenced.add(path.basename(rel));

  if (!/<meta property="og:image:alt"/.test(html)) {
    failures.push(`${route} — og:image has no alt text`);
  }
}

const dir = path.join(OUT, 'og');
const orphans = fs.existsSync(dir)
  ? fs.readdirSync(dir).filter((f) => f.endsWith('.png') && !referenced.has(f))
  : [];

if (failures.length) {
  console.error(`\nShare images: ${failures.length} problem(s) across ${checked} pages.\n`);
  for (const f of failures) console.error(`  ${f}`);
  console.error('\nRun `npm run og` if a card is missing.\n');
  process.exit(1);
}

console.log(
  `  ok   every page names a share image — ${checked} pages, ${referenced.size} cards`,
);
if (orphans.length) {
  console.log(`  warn unreferenced card(s): ${orphans.join(', ')}`);
}
