/**
 * Checks the share images against the pages that reference them.
 *
 *   node scripts/verify-og.mjs [outDir]
 *
 * Runs in `postbuild`, beside `verify-assets.mjs`. It reads the exported HTML
 * rather than the source, because the source is not what crawlers see.
 *
 * ---
 *
 * WHY THIS EXISTS
 *
 * The cards are generated by `npm run og` and committed, which means they can
 * fall out of step with the site in a way nothing else would notice. Add a
 * lesson and forget to regenerate, and that lesson's page ships pointing at a
 * PNG that is not in the export — and a broken share image is invisible from
 * inside the site. You do not find out until someone posts a link and it comes
 * up as a grey rectangle, and by then it has been wrong for weeks.
 *
 * So: every page must name one, every name must resolve to a file that is
 * actually in the build, and every URL must be absolute — a relative
 * `og:image` is rejected outright by most crawlers.
 *
 * It also reports cards nothing points at. That is a warning rather than a
 * failure: an unreferenced PNG is dead weight in the repository, not a broken
 * page, and a route may legitimately be mid-removal.
 */

import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const OUT = process.argv[2] ?? 'out';

/*
  The same value `metadataBase` is built from, and the reason this script has to
  know it.

  An og:image is emitted as `metadataBase` + `/og/<name>.jpg`. On a GitHub
  project page that base carries the repository segment —
  `https://<owner>.github.io/<repo>` — but `basePath` is a SERVING prefix, not a
  directory: the export has no `<repo>/` inside it, the file is at `out/og/…`
  and the host maps the two together.

  The first version of this check stripped only the scheme and host, so it went
  looking for `out/seventeen-studios/og/home.jpg` and failed all eighteen pages
  on a deploy that was completely correct. Locally there was nothing to catch it,
  because `basePath` is empty and the two forms are identical.

  Resolving against the site URL instead makes the checker and the metadata agree
  by construction — they read the same environment variable — and it upgrades the
  check: an og:image that is NOT under the site's own base is now a failure in
  its own right rather than something quietly mis-parsed.
*/
const SITE = (process.env.NEXT_PUBLIC_SITE_URL || 'https://rutvik17.github.io/seventeen-studios').replace(
  /\/$/,
  '',
);

function pages(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) =>
    entry.isDirectory()
      ? pages(path.join(dir, entry.name))
      : entry.name === 'index.html'
        ? [path.join(dir, entry.name)]
        : [],
  );
}

if (!fs.existsSync(OUT)) {
  console.error(`no export at ${OUT} — run the build first`);
  process.exit(1);
}

const failures = [];
const referenced = new Set();
let checked = 0;

for (const file of pages(OUT)) {
  const html = fs.readFileSync(file, 'utf8');
  const route = '/' + path.relative(OUT, path.dirname(file)).split(path.sep).join('/');
  const url = (html.match(/<meta property="og:image" content="([^"]+)"/) ?? [, ''])[1];

  checked++;

  if (!url) {
    failures.push(`${route} — no og:image`);
    continue;
  }

  if (!/^https?:\/\//.test(url)) {
    failures.push(`${route} — og:image is relative (${url}); crawlers need an absolute URL`);
    continue;
  }

  /*
    Resolve against the site's own base, then look for the file in the export.

    This is what catches the `asset()` trap: wrapping an og:image path in
    `asset()` as well would double the repository segment, the URL would stop
    starting with the site base, and it would be caught here rather than in
    production where a broken share image is invisible.
  */
  if (!url.startsWith(`${SITE}/`)) {
    failures.push(`${route} — og:image is not under ${SITE}: ${url}`);
    continue;
  }

  const [rel, query = ''] = url.slice(SITE.length).split('?');
  const onDisk = path.join(OUT, rel);
  if (!fs.existsSync(onDisk)) {
    failures.push(`${route} — og:image does not resolve to a file in the export: ${rel}`);
    continue;
  }
  referenced.add(path.basename(rel));

  // The version is what makes a redrawn card a new URL; a stale one would let caches keep the old picture.
  const version = new URLSearchParams(query.replace(/&amp;/g, '&')).get('v');
  const hash = crypto.createHash('sha1').update(fs.readFileSync(onDisk)).digest('hex').slice(0, 10);
  if (version !== hash) {
    failures.push(`${route} — og:image version ${version ?? '(none)'} does not match the file (${hash})`);
  }

  if (!/<meta property="og:image:alt"/.test(html)) {
    failures.push(`${route} — og:image has no alt text`);
  }

  // X reads its own tags. Set only on the landing, every page previewed there as the landing.
  const tag = (attr, name) => (html.match(new RegExp(`<meta ${attr}="${name}" content="([^"]*)"`)) ?? [, null])[1];
  for (const k of ['title', 'description', 'image']) {
    if (tag('name', `twitter:${k}`) !== tag('property', `og:${k}`)) {
      failures.push(`${route} — twitter:${k} does not match og:${k}`);
    }
  }
}

const dir = path.join(OUT, 'og');
const orphans = fs.existsSync(dir)
  ? fs.readdirSync(dir).filter((f) => /\.(png|jpg)$/.test(f) && !referenced.has(f))
  : [];

if (failures.length) {
  console.error(`\nShare images: ${failures.length} problem(s) across ${checked} pages.\n`);
  for (const f of failures) console.error(`  ${f}`);
  console.error('\nRun `npm run og` if a card is missing.\n');
  process.exit(1);
}

console.log(
  `  ok   every page names a share image — ${checked} pages, ${referenced.size} cards`,
);
if (orphans.length) {
  console.log(`  warn unreferenced card(s): ${orphans.join(', ')}`);
}
